config/routes.rb
Rails.application.routes.draw do
  devise_for :employees
  devise_for :clients
  devise_for :users
  resources :products
  resources :shops, only: %i[index show]
  resource :carts, only: :show do
    collection do
      delete :destroy_all
    end
  end

  resources :product_categories
  resources :categories

  resources :order_items do
    resources :products
  end

  root to: 'pages#home'

  # API
  namespace :api do
    namespace :v1 do
      devise_for :users
      resources :products
      resources :shops, only: %i[index show]
      resource :carts, only: :show do
        collection do
          delete :destroy_all
        end
      end

      resources :product_categories
      resources :categories

      resources :order_items do
        resources :products
      end

      root to: 'pages#home'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories, dependent: :destroy
  has_many :products, through: :product_categories

end

app/models/client.rb
class Client < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/copmany.rb
class Copmany < ApplicationRecord
  belongs_to :users
  belongs_to :stores
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :work_places
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  before_save :set_subtotal

  def subtotal
    order_items.collect{|order_item| order_item.valid? ? order_item.unit_price*order_item.quantity : 0}.sum
  end

  private

  def set_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  before_save :set_unit_price
  before_save :set_total

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end


  def total
    unit_price*quantity
  end


  private

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total
    self[:total] = total * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items
  has_many :assignments
  has_many_attached :photos
  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories


  accepts_nested_attributes_for :assignments
  has_many :colors, through: :assignments

  validates :title, presence: true
  validates :price, presence: true
  validates :stock, presence: true
  validates :photos, presence: true
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :companies
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :companies
end

app/models/work_place.rb
class WorkPlace < ApplicationRecord
  belongs_to :stores
  belongs_to :employees
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:home]
  include Pundit
  include ApplicationHelper

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authenticate_user!

  def show
    @order_items = current_order.order_items
    authorize @order_items
  end

  def destroy_all
    @delete_all_orders = current_order.order_items.all
    @delete_all_orders.destroy_all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: %i[show edit update destroy]

  def index
    @categories = policy_scope(Category)
  end

  def show
  end

  def new
    @category = Category.new
    authorize @category
  end

  def create
    @category = Category.new(category_params)
    authorize @category

    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @category.update(category_params)
    redirect_to category_path(@category)
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  private

  def find_category
    @category = Category.find(params[:id])
    authorize @category
  end

  def category_params
    params.require(:category).permit(:name, :description)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @user = User.find(current_user.id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]


  def index
    @products = policy_scope(Product)
    # respond_to do |format|
    #   format.html
    #   format.json { render json: { products: @products } }
    # end
  end

  def show
  end


  def new
    @product = Product.new
    authorize @product
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    authorize @product
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def update
    @product.update(product_params)
    redirect_to products_path
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
      authorize @product
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :price, :stock, photos: [])
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @products = policy_scope(Product)

    @order_item = current_order.order_items.new
  end

  def show
    @product = Product.find(params[:id])
    authorize @product
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
      p "my order:"
      p Order.find(session[:order_id])
    else
      Order.new
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>From Hamburg With Love - Online Store</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'logo.png' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <!-- Material Design -->
    <link href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css" rel="stylesheet">
    <script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>
    <!-- Material Icons -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  </head>

  <body>
    <!-- Nav Bar -->
    <% unless current_page?(dashboards_path) %>
      <%= render :partial => 'shared/navbar2' %>
    <% end %>

    <!-- Body Content -->
    <%= yield %>

    <!-- Footer -->
    <%#= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>
<%= render 'shared/featured' %>
<%= render 'shared/products_home_page' %>

app/views/shared/_banner.html.erb
<div class="banner-container row" style="background-image: url(https://images.unsplash.com/photo-1583209814683-c023dd293cc6?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80);">
  <div class="text-banner col-12 col-lg-6 justify-content-start py-5 m-5">
    <h4 style="font-weight: light;">From Hamburg With Love</h5>
    <h1>WAKE UP</h1>
    <h1>AND MAKEUP</h1>
    <div class="text-p-banner d-flex">
      <div class="v2"></div>
      <p style="width: 80%; margin: 0;">Lorem ipsum dolor sit amet consectetur adipisicing, elit. Recusandae maxime cupiditate cumque eos quod, voluptate</p>
    </div>
    <div class="d-flex align-items-center">
      <%= link_to shops_path do %>
        <button class="btn btn-banner btn-dark">Start Shopping <i class="fas fa-chevron-right"></i></button>
      <% end %>
      <%= link_to shops_path do %>
        <button class="btn btn-trend btn-warning">
          <i class="fas fa-chevron-right"></i>
        </button>
      <% end %>
      <p class="ml-2" style="margin:0; text-shadow: 1px 1px 2px rgba(0,0,0,0.2); font-size: 14px;">
        See what's trending
      </p>
    </div>
  </div>
</div>

app/views/shared/_featured-list.html.erb
<div class="featured-container row justify-content-between align-items-center" style="width: 100%;">

  <div class="featured-card col-lg-4 col-12">
    <%= image_tag "featured-1.png", alt: "alttext" %>
    <div class="text-card">
      <p>FACE</p>
      <p>See All</p>
    </div>
    <div class="v3"></div>
  </div>


  <div class="featured-card col-lg-4 col-12">
    <%= image_tag "featured-2.png", alt: "alttext" %>
    <div class="text-card">
      <p>HANDS</p>
      <p>See All</p>
    </div>
    <div class="v3"></div>
  </div>


  <div class="featured-card col-lg-4 col-12">
    <%= image_tag "featured-3.png", alt: "alttext" %>
    <div class="text-card">
      <p>BODY</p>
      <p class="inline">See All</p>
    </div>
    <div class="v3"></div>
  </div>
</div>

app/views/shared/_featured.html.erb
<div class="align-items-end row">
  <!-- Picture -->
  <div class="col-lg-3 col-12 d-flex justify-content-center">
    <%= image_tag "featured.png", alt: "alttext", class: "featured-picture"%>
  </div>

  <!-- Banner -->
  <div class="col-lg-9 col-12">

    <!-- Title -->
    <div class="row featured-title d-flex justify-content-center align-items-center">
      <div class="d-flex align-items-center col-12 col-lg-12" style="padding-left: 0px;">
        <i class="fas fa-burn"></i>
        <p>Featured</p>
      </div>
    </div>

    <!-- Cards -->
    <div class="featured-bar d-flex">
      <%= render "shared/featured-list" %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<!-- Log Out User/Admin -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <ul class="navbar-nav mr-auto">
    <% if user_signed_in? %>
      <% if current_user.admin? %>
        <li class="nav-item btn-group dropup">
          <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Welcome <%= current_user.user_name %></button>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#!">Dasboard</a>
            <a class="dropdown-item" href="#!">Mesages</a>
            <%= link_to "Log out", destroy_user_session_path, :method => :delete, class: 'dropdown-item'  %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, :method => :delete, class: 'nav-link'  %>
        </li>
      <% end %>
    <% else %>
      <li class="nav-item">
        <%= link_to "Log In", user_session_path, class: 'nav-link'  %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class: 'nav-link' %>
      </li>
    <% end %>
  </ul>

  <!-- Add Product Btn -->
  <% if user_signed_in? && current_user.admin? %>
    <%= link_to new_product_path do %>
      <button class="mdc-fab mdc-fab--extended">
        <div class="mdc-fab__ripple"></div>
        <span class="material-icons mdc-fab__icon">add</span>
        <span class="mdc-fab__label">Products</span>
      </button>
    <% end %>
  <% end %>
</nav>
<!-- Log Out User/Admin -->

app/views/shared/_navbar.html.erb
<nav id="box" class="navbar navbar-expand-md navbar-light box-shadow">


  <div class="collapse navbar-collapse justify-content-between px-5" id="collapse_target">
    <!-- Logo -->
    <%= link_to root_path do %>
       <%= image_tag "logo.png", class: "", :style => "height: 60px;" %>
    <% end %>
    <!-- Logo -->

    <ul class="navbar-nav ml-auto pt-2">
      <!-- Shop Now button -->
      <li class="nav-item">
        <%= link_to shops_path do %>
          <button class="mdc-button mdc-button--outlined">
            <div class="mdc-button__ripple"></div>
            <span class="mdc-button__label">Shop Now</span>
          </button>
        <% end %>
      </li>
      <!-- Shop Now button -->

      <!-- Log Out User/Admin -->
      <% if user_signed_in? %>
        <% if current_user.admin? %>
          <li class="nav-item">
            <p class="nav-link dropdown-tottle waves-effect" id="navbar-dropdown-admin" data-toggle="dropdown">Welcome <%= current_user.user_name %></p>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#!">Dasboard</a>
              <a class="dropdown-item" href="#!">Mesages</a>
              <%= link_to "Log out", destroy_user_session_path, :method => :delete, class: 'dropdown-item'  %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, :method => :delete, class: 'nav-link'  %>
          </li>
        <% end %>
      <% else %>
        <li class="nav-item">
          <%= link_to "Log In", user_session_path, class: 'nav-link'  %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
      <!-- Log Out User/Admin -->

      <!-- Shopping Cart -->
      <li class="nav-item">
        <%= link_to carts_path, :class=> "nav-link navbar-link-2 waves-effect" do %>
            <i class="fas fa-shopping-cart pl-o"></i>
        <% end %>
      </li>
      <li class="nav-item" id="cart">
        <%= render 'carts/cart' %>
      </li>
      <!-- Shopping Cart -->

    </ul>
  </div>

  <button class="navbar-toggler" data-toggle="collapse" data-target="#collapse_target">
    <span class="navbar-toggler-icon"></span>
  </button>

</nav>

app/views/shared/_navbar2.html.erb
<nav id="box" class="navbar navbar-expand-md navbar-light box-shadow">
  <div class="collapse navbar-collapse justify-content-between px-5" id="collapse_target">
    <div>
      <!-- Logo -->
      <%= link_to root_path do %>
         <%= image_tag "logo.png", class: "", :style => "height: 60px;" %>
      <% end %>
      <!-- Logo -->
    </div>

    <div>
      <!-- Links -->
      <ul class="navbar-nav ml-auto pt-2">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to "Shop", shops_path, class: "nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to "About", root_path, class: "nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact", root_path, class: "nav-link"  %>
        </li>
      </ul>
      <!-- Links -->
    </div>

    <div>
      <%= render 'shared/shopping_cart_search_navbar' %>
    </div>
  </div>

  <button class="navbar-toggler" data-toggle="collapse" data-target="#collapse_target">
    <span class="navbar-toggler-icon"></span>
  </button>
</nav>

app/views/shared/_products_home_page.html.erb
<div class="products-container">
  <div class="nav-bar-products d-flex justify-content-center align-items-center">
    <h1 class="mb-5">Shop</h1>
  </div>

  <div class="products-grid">

  </div>
</div>

app/views/shared/_shopping_cart_search_navbar.html.erb
<div class="outline-search-cart">
  <div class="d-flex justify-content-between align-items-center">
    <!-- Search Bar -->
    <i class="fas fa-search px-2"></i>
    <input type="text" placeholder="Search">
    <div class="vl"></div>

    <!-- Shopping Cart -->
    <div>
      <%= link_to carts_path, :class=> "nav-link navbar-link-2 waves-effect cart" do %>
        <i class="fas fa-shopping-cart" style="color: gray"></i>
      <% end %>
    </div>

    <!-- Badge -->
      <%= render 'carts/cart' %>
  </div>
</div>