config/routes.rb
Rails.application.routes.draw do
  devise_for :employees
  devise_for :clients
  devise_for :users
  resources :products
  resources :shops, only: %i[index show]
  resource :carts, only: :show do
    collection do
      delete :destroy_all
    end
  end

  resources :product_categories
  resources :categories

  resources :order_items do
    resources :products
  end

  root to: 'pages#home'

  # API
  namespace :api do
    namespace :v1 do
      devise_for :users
      resources :products
      resources :shops, only: %i[index show]
      resource :carts, only: :show do
        collection do
          delete :destroy_all
        end
      end

      resources :product_categories
      resources :categories

      resources :order_items do
        resources :products
      end

      root to: 'pages#home'
    end
  end
end

app/controllers/api/v1/carts_controller.rb
class Api::V1::CartsController < ApplicationController
  skip_before_action :authenticate_user!

  def show
    order_items = current_order.order_items
    skip_authorization
    render json: { order_items: order_items }
  end

  def destroy_all
    @delete_all_orders = current_order.order_items.all
    @delete_all_orders.destroy_all
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authenticate_user!

  def show
    @order_items = current_order.order_items
    authorize @order_items
  end

  def destroy_all
    @delete_all_orders = current_order.order_items.all
    @delete_all_orders.destroy_all
  end
end

app/views/carts/_cart.html.erb
<span id="cart">
  <% if current_order.order_items.size > 0 %>
    <h6 class="badge-position badge badge-pill badge-danger rounded-circle">
      <%= current_order.order_items.size%>
    </h6>
  <% end %>
</span>

app/views/carts/_carts_items.html.erb
<div class="order-items-title">
  <% if user_signed_in? %>
    <h1 style="margin-bottom: 0;">Shopping Cart</h1>
  <% else %>
    <h1>Shopping Cart</h1>
  <% end %>
  <div>
    <% if user_signed_in? %>
      <div class="d-flex justify-content-end align-items-baseline">
        <i class="fas fa-map-marker-alt"></i>
        <div style="margin-left: 12px;">
          <p>Delivery address:</p>
          <p> <%= current_user.user_name %> </p>
        </div>
      </div>
    <% end %>
  </div>
  <hr>
</div>
<div class="row just">
  <!-- Items -->
  <div class="order-items-products col-12 col-lg-8">
    <%= render "order_items" %>
  </div>

  <!-- Subtotal - Checkout -->
  <div class="sticky-top order-items-subtotal col-12 col-lg-4">
    <%= render "check_out" %>
  </div>
</div>

app/views/carts/_check_out.html.erb
<div class="check-out-sticky">
  <div class="check_out d-flex justify-content-between flex-column">
    <div>
      <h1>Total</h1>
      <hr>
      <h4>€ <%= current_order.subtotal %></h4>
    </div>
    <div>
      <p>Proceed to payment & delivery options</p>
      <button id="check-out" type="button" class="btn btn-primary btn-lg btn-block">Check Out</button>
    </div>
  </div>
  <p class="d-flex align-items-center link-with-arrow"><<%= link_to 'Continue Shopping', shops_path, :class => "blockquote-footer" %></p>
</div>

app/views/carts/_order_items.html.erb
<div id="cart-item">
  <% @order_items.order(:created_at).each do |item| %>
    <div class="row order-item-card">
      <!-- Picture -->
      <div class="order-item-picture col-12 col-lg-2 ">
        <%= cl_image_tag item.product.photos.first.key , alt: "product-picture" %>
      </div>
      <!-- Info -->
      <div class="order-item-info col-12 col-lg-8 d-flex flex-column align-content-between">
        <%= item.product.title %>
        <% if item.product.stock > 10 %>
          <p style="color: #7acf33; text-shadow: 0 0 1px #8BE83E;" class="blockquote-footer">In Stock</p>
        <% elsif  %>
          <p style="color: #ffc200; text-shadow: 0 0 1px #ffc200" class="blockquote-footer">Last Items</p>
        <% end %>
        <%= form_for item, remote: true do |f| %>
          <%= f.hidden_field :product_id, :value => item.product.id %>
          <%= f.number_field :quantity, :value => item.quantity.to_i, max: item.product.stock + 1 %>
          <%= f.submit "Update Cart", class: "btn btn-light btn-sm" %>

          <%= link_to "Remove Item", order_item_path(item), class: "btn btn-light btn-sm", method: :delete, remote: true%>
        <% end %>
      </div>
      <!-- Prices -->
      <div class="order-item-price col-12 col-lg-2 d-flex flex-column align-content-end justify-content-between">
        <p style="font-size: 20px; font-weight: 600;">€ <%= item.quantity * item.product.price %></p>
        <p style="margin-bottom: 12px;">Item: € <%= item.product.price %> </p>
      </div>
    </div>
  <% end %>
</div>

  <!-- <p>Subtotal: <%#= item.total %> </p> -->


<!-- <p>Total: <%#= current_order.subtotal%> </p> -->

app/views/carts/show.html.erb
<div class="cart-container">
  <%= render 'cart_nav_bar' %>
  <%= render 'carts_items' %>
</div>