config/routes.rb
Rails.application.routes.draw do
  devise_for :employees
  devise_for :clients
  devise_for :users
  resources :products
  resources :shops, only: %i[index show]
  resource :carts, only: :show do
    collection do
      delete :destroy_all
    end
  end

  resources :product_categories
  resources :categories

  resources :order_items do
    resources :products
  end

  root to: 'pages#home'

  # API
  namespace :api do
    namespace :v1 do
      devise_for :users
      resources :products
      resources :shops, only: %i[index show]
      resource :carts, only: :show do
        collection do
          delete :destroy_all
        end
      end

      resources :product_categories
      resources :categories

      resources :order_items do
        resources :products
      end

      root to: 'pages#home'
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items
  has_many :assignments
  has_many_attached :photos
  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories


  accepts_nested_attributes_for :assignments
  has_many :colors, through: :assignments

  validates :title, presence: true
  validates :price, presence: true
  validates :stock, presence: true
  validates :photos, presence: true
end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_product, only: %i[show edit update destroy]

  def index
    products = policy_scope(Product)
    products_with_pictures = []
    products.each do |product|
      products_with_pictures << {'product' => product, 'photos' => product.photos.map{|p| p.key}}
    end
    render json: { products: products_with_pictures }
  end

  def show
    images = []
    @product.photos.each do |photo|
      images << photo.key
    end
    render json: { product: @product, images: images }
  end

  def edit
    render json: { product: product }
  end

  def create
    product = Product.new(product_params)
    authorize @product
    if @product.save
      render json: { status: :created, product: product }
    else
      render json: { status: 401 }
    end
  end

  def update
    if product.update(product_params)
      render json: { product: product }
    else
      render json: { status: 401 }
    end
  end

  def destroy
    product.destroy
    render json: { product: 'deleted' }
  end

  private
    def set_product
      @product = Product.find(params[:id])
      skip_authorization
    end

    def product_params
      params.require(:product).permit(:title, :price, :stock, photos: [])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]


  def index
    @products = policy_scope(Product)
    # respond_to do |format|
    #   format.html
    #   format.json { render json: { products: @products } }
    # end
  end

  def show
  end


  def new
    @product = Product.new
    authorize @product
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    authorize @product
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def update
    @product.update(product_params)
    redirect_to products_path
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
      authorize @product
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :price, :stock, photos: [])
    end
end

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :price %>
    <%= f.input :stock %>
    <%= f.input :photos, as: :file, input_html: {multiple: true} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <h1>Editing Product</h1>

    <%= render 'form', product: @product %>

    <%= link_to 'Show', @product %> |
    <%= link_to 'Back', products_path %>
  <% else %>
    <% controller.redirect_to new_user_session_path %>
  <% end %>
<% else %>
  <% controller.redirect_to new_user_session_path %>
<% end %>

app/views/products/new.html.erb
<% if user_signed_in? %>
  <% if current_user.admin? %>
  <div class="row form-container justify-content-center">
    <div class="col-10 col-lg-12">
      <div>
        <h2>Create a new product</h2>
        <%= simple_form_for(@product) do |f| %>
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

          <div class="form-inputs">
            <%= f.input :title, label: false, placeholder: "Product Name", class: "form-imput-underlined" %>
            <%= f.input :price, label: false , placeholder: "Price", class: "form-imput-underlined" %>
            <%= f.input :stock, label: false , placeholder: "Stock", class: "form-imput-underlined" %>
            <div class="dropzone dropzone-default dz-clickable" data-controller="dropzone" data-max-file-size="5" data-dropzone-max-files="4">
              <%= f.input :photos, as: :file, input_html: { multiple: true, data: { target: "dropzone.input" }, direct_upload: true }, label: false %>
              <div class="dropzone-msg dz-message needsclick text-gray-600">
                <span class="d-flex justify-content-center">
                  <h3 class="dropzone-msg-ttile mr-1">Drop & Drop or</h3>
                  <h3 style="color: #047bff; text-decoration: underline;"> browse</h3>
                </span>
                <span class="dropzone-msg-desc text-sm"> 5 MB file size maximum. Allowed file type .png .jpg</span>
              </div>
            </div>
          </div>

          <div class="form-actions">
            <%= f.button :submit, '+ Add Product', class: "btn btn-primary btn-lg btn-block mt-3"%>
          </div>
        <% end %>

        <p class="d-flex align-items-center link-with-arrow"><<%= link_to 'Back', products_path, :class => "blockquote-footer" %></p>
      </div>
    </div>
  </div>
  <% else %>
    <% controller.redirect_to new_user_session_path %>
  <% end %>
<% else %>
  <% controller.redirect_to new_user_session_path %>
<% end %>

app/views/products/show.html.erb
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Title:</strong>
      <%= @product.title %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= @product.price %>
    </p>


    <p>
      <strong>Categories:</strong>
      <% @product.categories.each do |category| %>
        <%= category.name %>
      <% end %>
    </p>

    <%= link_to 'Edit', edit_product_path(@product) %> |
    <%= link_to 'Back', products_path %>
  <% else %>
    <% controller.redirect_to new_user_session_path %>
  <% end %>
<% else %>
  <% controller.redirect_to new_user_session_path %>
<% end %>